# Usa una imagen base de Java 17
FROM openjdk:17-jdk-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el JAR generado por Maven
# Asegúrate que el nombre coincida con el de tu carpeta target
COPY target/admin-tareas-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto (Spring Boot por defecto 8080)
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]